### ISSUE TITLE
Issue with extra space at end of Publication Title

### ISSUE THREAD

**Issue by FaberfoX** [PrawnCocktail/ReadlyFetcher#1]
Seen on PUBID 5c066d9903c6b7460f7790a4

ReadlyFetcher.exe -a=xxxxxxxxxxxxxxxxxxxxxxxxxxx -t=pdf -p=5c066d9903c6b7460f7790a4
Found: 3 issues.
=============================================================================
Fetching: PC Gamer Annual  - 2021 Edition

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'T:\Readly\PC Gamer Annual \PC Gamer Annual  - 2021 Edition.pdf'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at iText.Kernel.Pdf.PdfWriter..ctor(String filename)
   at ReadlyFetcher.Program.GetPDF(String id, String title, String issue)
   at ReadlyFetcher.Program.getMagazineIssues(String pubid)
   at ReadlyFetcher.Program.Main(String[] args)

**Comment by PrawnCocktail** [comment]
Hey, 
Thanks for letting me know. I have uploaded a new release that should fix the issue. 
https://github.com/PrawnCocktail/ReadlyFetcher/releases/tag/v1.12
